# Exported from Render on 2025-04-20T17:01:00Z
services:
- type: web
  name: grafica-implotter
  runtime: docker
  repo: https://github.com/GraficaImPlotter/grafica-implotter
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_HOST
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
